<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CMLDRAMACHANDRA" ignored="0" name="RetryMulitple" tests="9" failures="2" timestamp="26 Jun 2017 06:54:16 GMT" time="0.121" errors="0">
  <testcase name="testCase1" time="0.015" classname="RetryFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase1" time="0.002" classname="RetryFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase1" time="0.002" classname="RetryFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase1" time="0.002" classname="RetryFailedTestCases.TestCases">
    <failure type="java.lang.AssertionError" message="expected [Msg1] but found [Msg]">
      <![CDATA[java.lang.AssertionError: expected [Msg1] but found [Msg]
	at RetryFailedTestCases.TestCases.testCase1(TestCases.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase2" time="0.002" classname="RetryFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.002" classname="RetryFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.002" classname="RetryFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.003" classname="RetryFailedTestCases.TestCases">
    <failure type="java.lang.AssertionError" message="expected [Msg11] but found [Msg1]">
      <![CDATA[java.lang.AssertionError: expected [Msg11] but found [Msg1]
	at RetryFailedTestCases.TestCases.testCase2(TestCases.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="0.002" classname="RetryFailedTestCases.TestCases"/>
</testsuite> <!-- RetryMulitple -->
